field.yoast_seo_status.value:
  type: string
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Value'

field.yoast_seo_focus_keyword.value:
  type: string
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Value'
